### ISSUE TITLE
统计时不应该计算体育教研部

### ISSUE THREAD

**Issue by Achyutace** [KingRayCao/PKU-Annual-Eat#1]
体育教研部那个好像是租场地花的钱

**Comment by KingRayCao** [comment]
应该可以写一个统一的filter，把一些归并工作整合一下
但是我最近没啥时间写了（悲）

**Comment by LHRG** [comment]
支持！同一食堂不同窗口名称不同可以根据“校园指数”中的规范名称合并一下～

**Comment by Chunfei-He** [comment]
> 应该可以写一个统一的filter，把一些归并工作整合一下 但是我最近没啥时间写了（悲）

我可以写一下体育教研部的filter，但我不太确定是不是你想要的。提了pull request，需要改动的地方直接联系我就好。

**Comment by KingRayCao** [comment]
已实现
